using System.Threading.Tasks.Dataflow;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace TestsGenerator.Library;

public class TestGenerator
{
    private readonly int _maxRead, _maxGen, _maxWrite;

    public TestGenerator(int maxRead, int maxGen, int maxWrite)
    {
        _maxRead = maxRead;
        _maxGen = maxGen;
        _maxWrite = maxWrite;
    }

    public TestGenerator() : this(Environment.ProcessorCount, Environment.ProcessorCount, Environment.ProcessorCount) { }
    //вызов основн конструктор, передавая кол-во ядер процессора
    public async Task GenerateTestsAsync(IEnumerable<string> inputFiles, string outputFolder)
    {
        Directory.CreateDirectory(outputFolder);

        var readBlock = new TransformBlock<string, string>(async path => 
            await File.ReadAllTextAsync(path), 
            new ExecutionDataflowBlockOptions { MaxDegreeOfParallelism = _maxRead });

        var generateBlock = new TransformManyBlock<string, TestFile>(sourceCode => 
            GenerateTestFilesLogic(sourceCode), 
            new ExecutionDataflowBlockOptions { MaxDegreeOfParallelism = _maxGen });

        var writeBlock = new ActionBlock<TestFile>(async file => 
            await File.WriteAllTextAsync(Path.Combine(outputFolder, file.FileName), file.Content), 
            new ExecutionDataflowBlockOptions { MaxDegreeOfParallelism = _maxWrite });

        var linkOptions = new DataflowLinkOptions { PropagateCompletion = true };
        readBlock.LinkTo(generateBlock, linkOptions);
        generateBlock.LinkTo(writeBlock, linkOptions);

        foreach (var file in inputFiles) readBlock.Post(file);

        readBlock.Complete();
        await writeBlock.Completion;
    }

    private IEnumerable<TestFile> GenerateTestFilesLogic(string sourceCode)
    {
        var root = CSharpSyntaxTree.ParseText(sourceCode).GetRoot();
        var classes = root.DescendantNodes().OfType<ClassDeclarationSyntax>()
            .Where(c => c.Modifiers.Any(m => m.IsKind(SyntaxKind.PublicKeyword)));

        foreach (var cls in classes)
        {
            string testCode = GenerateSingleTestClass(cls);
            yield return new TestFile { 
                FileName = $"{cls.Identifier.Text}Tests.cs", 
                Content = testCode 
            };
        }
    }

    private string GenerateSingleTestClass(ClassDeclarationSyntax cls)
    {
        string className = cls.Identifier.Text;
        var methods = cls.Members.OfType<MethodDeclarationSyntax>()
            .Where(m => m.Modifiers.Any(mod => mod.IsKind(SyntaxKind.PublicKeyword)))
            .ToList();

        var methodCounts = new Dictionary<string, int>();
        var testMethods = new List<string>();

        foreach (var method in methods)
        {
            string name = method.Identifier.Text;
            if (!methodCounts.ContainsKey(name)) methodCounts[name] = 1;
            else methodCounts[name]++;

            bool isOverloaded = methods.Count(m => m.Identifier.Text == name) > 1;
            string testName = isOverloaded ? $"{name}{methodCounts[name]}Test" : $"{name}Test";

            var arrange = method.ParameterList.Parameters.Select(p => 
                $"            {p.Type} {p.Identifier.Text} = default;");

            string args = string.Join(", ", method.ParameterList.Parameters.Select(p => p.Identifier.Text));
            string act = method.ReturnType.ToString() == "void" 
                ? $"            _testClass.{name}({args});" 
                : $"            var actual = _testClass.{name}({args});";

            string assert = method.ReturnType.ToString() == "void"
                ? "            Assert.True(true);"
                : "            var expected = default;\n            Assert.Equal(expected, actual);";

            testMethods.Add($@"
        [Fact]
        public void {testName}()
        {{
            // Arrange
{string.Join("\n", arrange)}

            // Act
{act}

            // Assert
{assert}
            Assert.True(false, ""autogenerated"");
        }}");
        }

        return $@"using System;
using Xunit;
using Moq;

namespace GeneratedTests
{{
    public class {className}Tests
    {{
        private {className} _testClass;

        public {className}Tests()
        {{
            _testClass = new {className}(); 
        }}
{string.Join("\n", testMethods)}
    }}
}}";
    }
}